--[[
                            (\.   \      ,/)
                            \(   |\     )/
                            //\  | \   /\\
                            (/ /\_#oo#_/\ \)
                            \/\  ####  /\/
                                `##'

===================================================================================
                        Hammerspoon Default Configuration
===================================================================================

This file contains DEFAULT configuration values for Hammerspoon.
DO NOT EDIT THIS FILE - it will be overwritten when updating.

To customize your configuration:
1. Create a file named "config.user.lua" in the same directory
2. Override any settings you want to change
3. Your personal settings will be merged with these defaults

See the README.md file for more information on configuration options.
]]--

local defaults = {
	--[[-----------------------------------------
    Common Modifier Combinations
    Used throughout the configuration for consistent shortcuts
    ------------------------------------------]]
	defaultEditor = "Editor", -- Default editor (Cursor/VS Code)

	triggers = {
		app = { "ctrl", "alt", "cmd"}, -- For launching applications (⌘⌃⌥)
		app2 = { "ctrl", "alt", "cmd", "shift" }, -- Second layer for apps (⌘⌃⌥⇧)
		folder = { "cmd", "shift" }, -- For opening folders (⌘⇧)
		window = { "alt" }, -- For window management (⌥) - will use either left or right
		lwindow = { "lalt" }, -- For window management with left alt only
		rwindow = { "ralt" }, -- For window management with right alt only
		screen = { "cmd", "alt" }, -- For screen management (⌘⌥)
		pattern = { "ctrl", "alt" }, -- For fabric patterns (⌃⌥)
	}, 


	--[[-----------------------------------------
    Applications
    Define paths to your commonly used applications
    You can use either a string for the app name or a table with more options:
    - name: The application name (required)
    - bundleID: The application's bundle ID (optional)
    - path: Full path to the application (optional)
    ------------------------------------------]]
	applications = {
		Browser = "Safari", -- Primary browser
		Browser2 = "Chrome", -- Secondary browser
		Editor = "Visual Studio Code", -- Code editor
		Editor2 = "Sublime Text", -- Second editor instance
		Terminal = "Terminal", -- Terminal emulator
		Notes = "Notes", -- Note-taking app
		Mail = "Mail", -- Email client
		Spotify = "Spotify", -- Music player
		Finder = "Finder", -- File manager
		WhatsApp = "WhatsApp", -- Messaging
		Settings = "System Settings", -- System preferences
		-- Minecraft = "java", -- Minecraft game itself (uncomment if you have Minecraft)
		-- MCLaunch = "Minecraft Launcher", -- Minecraft Launcher (uncomment if you have Minecraft)
		-- Discord = "Discord", -- Discord messaging app (uncomment if you have Discord)
	},

	--[[-----------------------------------------
    Application Groups
    Define groups of applications that can be cycled through with a single shortcut
    Each group can have two modes:
    - "recent": Prioritizes running apps, cycles through them by most recent usage
    - "preset": Always follows the defined order regardless of running state
    
    Settings:
    - launchIfNotRunning: If true, will launch apps that aren't running. If false, only cycles through running apps.
    ------------------------------------------]]
	appGroups = {
		-- Example browser group
		-- browsers = {
		-- 	apps = { "Browser", "Browser2" }, -- List of app names from applications section
		-- 	mode = "recent", -- "recent" or "preset"
		-- 	launchIfNotRunning = true, -- Launch apps if they're not running
		-- },
		-- Example editor group
		-- editors = {
		-- 	apps = { "Editor", "Editor2" },
		-- 	mode = "preset",
		-- 	launchIfNotRunning = true,
		-- },
	},

	--[[-----------------------------------------
    Folders
    Define paths to your commonly accessed folders
    ------------------------------------------]]
	folders = {
		home = "~", -- Home directory
		desktop = "~/Desktop", -- Desktop folder
		downloads = "~/Downloads", -- Downloads folder
		documents = "~/Documents", -- Documents folder
		pictures = "~/Pictures", -- Pictures folder
		applications = "/Applications", -- Applications folder
		hammerspoon = "~/.hammerspoon", -- Hammerspoon configuration folder
	},

	--[[-----------------------------------------
    Keyboard Shortcuts
    Define all keyboard shortcuts for Applications, Folders, General, and Window Management
    ------------------------------------------]]
	shortcuts = {
		-- Application shortcuts (ctrl + alt + cmd + key)
		apps = {
			{ app = "Browser", key = "Z" }, -- Primary browser
			{ app = "Browser2", key = "X" }, -- Secondary browser
			{ app = "Editor", key = "C" }, -- Code editor
			{ app = "Editor2", key = "V" }, -- Second editor
			{ app = "Terminal", key = "T" }, -- Terminal
			{ app = "Notes", key = "N" }, -- Notes
			{ app = "Mail", key = "M" }, -- Mail
			{ app = "Spotify", key = "S" }, -- Spotify
			{ app = "Finder", key = "F" }, -- Finder
			{ app = "WhatsApp", key = "W" }, -- WhatsApp
			{ app = "Settings", key = "P" }, -- System Settings
			-- { app = "Minecraft", key = "G" }, -- Minecraft game (uncomment if you have Minecraft)
		},
		
		-- Second-layer application shortcuts (ctrl + alt + cmd + shift + key)
		apps2 = {
			-- { app = "Browser", key = "B" }, -- Example second layer
			-- { app = "Editor", key = "E" }, -- Example second layer
			-- { app = "Minecraft", key = "M" }, -- Minecraft game
			-- { app = "Discord", key = "D" }, -- Discord
		},

		-- Application group shortcuts (ctrl + alt + cmd + key)
		appGroups = {
			-- { group = "browsers", key = "B" }, -- Cycle through browsers
			-- { group = "editors", key = "E" }, -- Cycle through editors
		},

		-- Folder shortcuts (cmd + shift + key)
		folders = {
			{ path = "home", key = "H" }, -- Home
			{ path = "desktop", key = "D" }, -- Desktop
			{ path = "downloads", key = "L" }, -- Downloads
			{ path = "documents", key = "F" }, -- Documents
			{ path = "applications", key = "A" }, -- Applications
		},

		-- General shortcuts
		general = {
			{ mods = { "ctrl", "alt", "cmd", "shift" }, key = "S", action = "openHammerspoonConfig" }, -- Open Hammerspoon config in editor
			{ mods = { "ctrl", "alt", "cmd", "shift" }, key = "R", action = "reloadHammerspoonConfig" }, -- Reload Hammerspoon configuration
			{ mods = { "ctrl", "alt", "cmd", "shift" }, key = ",", action = "openDotfilesConfig" }, -- Open dotfiles repo in editor
			{ mods = { "cmd" }, key = ".", action = "openInTerminal" }, -- Open current Finder path in terminal
			{ mods = { "cmd" }, key = ";", action = "openInEditor" }, -- Open current Finder path in editor
		},

		-- Utility shortcuts
		utils = {
			{ mods = { "cmd", "shift" }, key = "X", action = "closeFinderWindows" }, -- Close all Finder windows
			{ mods = { "cmd", "shift" }, key = "W", action = "closeOtherAppWindows" }, -- Close other windows of current app
		},

		-- Window management shortcuts
		windows = {
			-- Basic window movements (alt + key)
			left = { trigger = "window", key = "A" }, -- Left half
			right = { trigger = "window", key = "D" }, -- Right half
			center = { trigger = "window", key = "C" }, -- Center
			full = { trigger = "window", key = "F" }, -- Full screen

			-- Screen management (cmd + alt + key)
			nextScreen = { trigger = "screen", key = "D" }, -- Move to next screen
			prevScreen = { trigger = "screen", key = "A" }, -- Move to previous screen

			-- Thirds window management (alt + key)
			third1 = { trigger = "window", key = "1" }, -- First third (left)
			third2 = { trigger = "window", key = "2" }, -- Middle third
			third3 = { trigger = "window", key = "3" }, -- Last third (right)
			twoThirdsLeft = { trigger = "window", key = "4" }, -- Two thirds on the left
			twoThirdsRight = { trigger = "window", key = "5" }, -- Two thirds on the right

			-- Corner window management (alt + key)
			-- topLeft = { trigger = "window", key = "Q" }, -- Top left corner
			-- topRight = { trigger = "window", key = "E" }, -- Top right corner
			-- bottomLeft = { trigger = "window", key = "Z" }, -- Bottom left corner
			-- bottomRight = { trigger = "window", key = "V" }, -- Bottom right corner
			top = { trigger = "window", key = "W" }, -- Top half
			bottom = { trigger = "window", key = "S" }, -- Bottom half
		},
	},

	--[[-----------------------------------------
    Window Management Settings
    Configure window behavior and animations
    ------------------------------------------]]
	windowManagement = {
		animationDuration = 0, -- Set to 0 for instant window movements
	},

	--[[-----------------------------------------
    Debug Settings
    Configure debug options for various features
    ------------------------------------------]]
	debug = {
		-- Window and keyboard management
		windowManagement = false, -- Set to true to enable detailed logging for window management operations
		leftRightModifier = false, -- Set to true to enable detailed logging for left/right modifier detection
		mousespeedfinder = false, -- Set to true to enable detailed logging for mouse speed finder
		
		-- File and system operations
		symlinkCreation = false, -- Set to true to enable detailed logging for symlink creation
		fileOperations = false, -- Set to true to enable detailed logging for file operations
		
		-- Application management
		appLaunching = false, -- Set to true to enable detailed logging for application launching
		appFocusing = false, -- Set to true to enable detailed logging for application focusing
		appGroups = false, -- Set to true to enable detailed logging for app groups
		
		-- Clipboard and macros
		clipboard = false, -- Set to true to enable detailed logging for clipboard operations
		macro = false, -- Set to true to enable detailed logging for macro recording and playback
		
		-- Fabric AI integration
		fabric = false, -- Set to true to enable detailed logging for Fabric pattern execution
		
		-- Config and startup
		configLoading = false, -- Set to true to enable detailed logging for configuration loading
		
		-- Minecraft integration
		minecraft = false, -- Set to true to enable detailed logging for Minecraft integration
		
		-- Kanata integration
		kanata = false, -- Set to true to enable detailed logging for Kanata integration
		
		-- Autoclicker integration
		click = false, -- Set to true to enable detailed logging for autoclicker
	},

	--[[-----------------------------------------
    Minecraft Integration
    Configure Minecraft-specific features and shortcuts
    Set enabled = false to disable all Minecraft features
    ------------------------------------------]]
	minecraft = {
		enabled = false, -- Set to false to disable Minecraft features
		debug = false, -- Set to true to enable detailed logging for Minecraft features
		kanataSwitching = false, -- Set to true to automatically switch to gaming mode when Minecraft is focused
		detection = {
			appNames = {"java"}, -- Application names to consider as Minecraft
			titlePatterns = {"minecraft", "Minecraft"}, -- Patterns to look for in window titles
		},
		periodicClick = {
			enabled = false, -- Set to true to enable periodic clicking when Minecraft is focused
			interval = 145, -- Click interval in seconds (2 minutes 25 seconds = 145)
		},
	},

	--[[-----------------------------------------
    Fabric AI Integration
    Configure AI patterns and shortcuts
    ------------------------------------------]]
	fabric = {
		-- Default settings
		fabricPath = "~/go/bin/fabric", -- Path to fabric executable (Go install) or "/opt/homebrew/bin/fabric-ai" (Homebrew install)
		chooserTrigger = { "cmd", "alt", "shift" }, -- Global trigger for pattern chooser
		chooserKey = "P", -- Key for pattern chooser

		-- Pattern definitions
		patterns = {
			{
				id = "correct",
				name = "Correct Text",
				desc = "Fix and correct text",
				trigger = "pattern",
				key = "R",
			},
			{
				id = "improve",
				name = "Improve Text",
				desc = "Improve and enhance text",
				trigger = "pattern",
				key = "I",
			},
			{
				id = "yt_summarize",
				name = "YouTube Summary",
				desc = "Summarize YouTube content",
				trigger = "pattern",
				key = "S",
				youtube = true, -- Enable YouTube URL handling
			},
			{
				id = "latex",
				name = "LaTeX",
				desc = "Enhanced LaTeX processing",
				trigger = "pattern",
				key = "L",
			},
			{
				id = "general",
				name = "General AI",
				desc = "Custom AI instruction",
				trigger = "pattern",
				key = "G",
				variables = {
					instruction = ""  -- Will be filled by user input
				}
			},
			{
				id = "translate",
				name = "Translate",
				desc = "Translate text",
				trigger = "pattern",
				key = "T",
			},
			{
				id = "note_name",
				name = "Note Name",
				desc = "Generate a note name",
				trigger = "pattern",
				key = "N",
			},
			{
				id = "markdown_format",
				name = "Markdown Format",
				desc = "Format text in Markdown",
				trigger = "pattern",
				key = "M",
			},
			{
				id = "fact_check",
				name = "Fact Check",
				desc = "Verify the accuracy of information",
				trigger = "pattern",
				key = "A",
			},
			{
				id = "continue",
				name = "Continue",
				desc = "Continue the pattern",
				trigger = "pattern",
				key = "C",
			},
		},
	},

	--[[-----------------------------------------
    Kanata Integration
    Configure Kanata mode indicator and status file monitoring
    Set enabled = false to disable all Kanata features
    ------------------------------------------]]
	kanata = {
		enabled = true, -- Set to false to disable Kanata features
		debug = false, -- Set to true to enable detailed logging for Kanata features
		defaultMode = "normal", -- Default mode on startup (normal, vim, typing, gaming)
		statusFile = "~/.config/kanata/hammerspoon_status", -- File to read/write current mode
		kanataLayerCommand = "/Users/felixmrak/.bin/kanata-layer", -- Command to execute when changing layers from menu bar (e.g., "~/.bin/kanata-layer")
	},

	--[[-----------------------------------------
    Self-Organized Custom Shortcuts
    Add your own custom shortcuts and functions here
    ------------------------------------------]]
	self = {
		-- Trigger keys for self-organized shortcuts
		triggers = {
			custom = { "cmd", "alt", "shift" }, -- Example trigger combination
		},

		-- Custom shortcuts
		shortcuts = {
			-- Example shortcut
			{
				name = "sayHello",  -- Function name in self.lua
				desc = "Show hello message", -- Description for documentation
				mods = { "cmd", "alt", "shift" }, -- Key modifiers
				key = "H", -- Trigger key
			},
		},
	},

	--[[-----------------------------------------
    Clipboard Management
    Configure clipboard history and shortcuts
    ------------------------------------------]]
    clipboard = {
        enabled = true, -- Set to false to disable clipboard features
        maxHistory = 9, -- Maximum number of clipboard items to track
        shortcuts = {
            mods = { "ctrl", "shift" }, -- Modifiers for clipboard shortcuts
            keys = { "1", "2", "3", "4", "5", "6", "7", "8", "9" }, -- Keys for clipboard items
        },
        -- Hotkey for removing lines starting with '#'
        stripHashCommentsShortcut = { mods = { "ctrl", "shift" }, key = "C" },
    },

    --[[-----------------------------------------
    Macro Recording and Playback
    Configure macro recording, playback, and shortcuts
    ------------------------------------------]]
    macros = {
        enabled = true, -- Set to false to disable macro features
        maxMacros = 10, -- Maximum number of macros to store
        shortcuts = {
            record = {
                mods = { "alt", "cmd" },
                key = "["
            },
            play = {
                mods = { "alt", "cmd" },
                key = "]"
            },
            chooser = {
                mods = { "alt", "cmd" },
                key = "\\"
            },
            editor = {
                mods = { "alt", "cmd" },
                key = "e"
            }
        }
    },

    --[[-----------------------------------------
    Mouse Speed Finder
    Analyze pointing performance and suggest speed adjustments
    ------------------------------------------]]
    mousespeedfinder = {
        enabled = false, -- Set to true to enable mouse speed suggestions
        device = "auto", -- "auto" | "mouse" | "trackpad"
        minDistancePx = 30, -- Ignore very small moves
        overshootThreshold = 12, -- Pixels beyond target considered overshoot
        microAdjustWindowMs = 180, -- Window to count corrections near click
        idleThresholdMs = 300, -- Idle gap that starts a new gesture
        maxPointsPerGesture = 250, -- Cap points per gesture
        clicksPerBatch = 40, -- Analyze and suggest every N clicks
        scalingStep = 0.10, -- Suggested change amount
        minScaling = 0.50, -- Lower bound when suggesting
        maxScaling = 5.00, -- Upper bound when suggesting
        overshootHighRate = 0.30, -- If overshoot rate > this, suggest decreasing speed
        overshootLowRate = 0.05, -- If overshoot rate < this and slow, suggest increasing
        timePerPixelSlowMs = 1.00, -- If median ms/px slower than this, consider slow
        alert = true, -- Show suggestion alerts
        shortcuts = {
            toggle = { mods = { "cmd", "alt", "shift" }, key = "U" }, -- Toggle on/off
            report = { mods = { "cmd", "alt", "shift" }, key = "Y" }, -- Show recent stats
        },
    },

    --[[-----------------------------------------
    Autoclicker Module
    Provides autoclicking functionality that only works in Kanata gaming mode.
    Set enabled = false to disable all autoclicker features.
    ------------------------------------------]]
	click = {
		enabled = false, -- Set to true to enable autoclicker features
		leftEnabled = true, -- Set to true to enable left click autoclicking
		rightEnabled = true, -- Set to true to enable right click autoclicking
		leftCPS = 15, -- Left mouse clicks per second
		leftVariance = 1, -- Variance in CPS for left clicks (±1)
		rightCPS = 20, -- Right mouse clicks per second
		rightVariance = 2, -- Variance in CPS for right clicks (±2)
	},

	--[[-----------------------------------------
	Telemetry (Hotkey Usage Tracking)
	Privacy-first, disabled by default. When enabled, records hotkey presses
	locally to a JSONL file and can optionally POST to your server.
	------------------------------------------]]
	telemetry = {
		enabled = false, -- Set true to enable tracking
		username = nil, -- Optional username identifier
		serverUrl = "https://hammerspoon.felixmrak.com/api/hammerspoon/usage", -- Optional: e.g. "http://localhost:3000/api/hammerspoon/usage"
		token = "ZtcxUDsRbHSgje4NMgjQ099gTyhdM4JV259jFk2W", -- Optional: send X-Hspo-Token header (or use HSPO_TOKEN env)
		includeAppName = true, -- Include frontmost app name with each event
		eventsFile = "~/.hammerspoon/telemetry_events.jsonl" -- Local JSONL log
	},
}

return defaults 