#!/bin/bash

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1"; }
step() { echo -e "${BLUE}[STEP]${NC} $1"; }

CONFIG_CREATED=0

confirm() {
	local prompt="$1"
	read -r -p "$prompt [y/N]: " ans || true
	[[ "$ans" =~ ^[Yy]$ ]]
}

require_cmd() {
	if ! command -v "$1" >/dev/null 2>&1; then
		err "Missing required command: $1"
		return 1
	fi
}

install_homebrew() {
	if command -v brew >/dev/null 2>&1; then
		info "Homebrew is already installed"
		return
	fi
	step "Installing Homebrew"
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	info "Homebrew installed"
}

install_pkg() {
	local pkg="$1"
	if brew list --formula "$pkg" >/dev/null 2>&1 || brew list --cask "$pkg" >/dev/null 2>&1; then
		info "$pkg already installed"
		return
	fi
	if brew info --cask "$pkg" >/dev/null 2>&1; then
		brew install --cask "$pkg"
	else
		brew install "$pkg"
	fi
}

backup_dir() {
	local path="$1"
	if [ -e "$path" ]; then
		local ts
		ts="$(date +%Y%m%d_%H%M%S)"
		local backup="${path}.backup.${ts}"
		mv "$path" "$backup"
		info "Backed up ${path} -> ${backup}"
	fi
}

clone_repo() {
	local dest="$HOME/.hammerspoon"
	local repo="https://github.com/felixleopold/hammerspoon.git"
	if [ -d "$dest/.git" ]; then
		info "Repository already present in $dest"
		return
	fi
	if [ -d "$dest" ]; then
		warn "$dest exists"
		if confirm "Backup and replace existing ~/.hammerspoon?"; then
			backup_dir "$dest"
		else
			err "Cancelled by user"
			exit 1
		fi
	fi
	git clone "$repo" "$dest"
	info "Cloned repository"
}

ensure_user_config() {
	local tpl="$HOME/.hammerspoon/config_user.lua.template"
	local cfg="$HOME/.hammerspoon/config_user.lua"
	if [ ! -f "$cfg" ]; then
		cp "$tpl" "$cfg"
		info "Created user config from template"
		CONFIG_CREATED=1
	fi
}

set_app_defaults() {
	local cfg="$HOME/.hammerspoon/config_user.lua"
	step "Configuring app defaults"
	read -r -p "Primary Browser [Safari/Chrome/Arc/Brave] (default: Safari): " primary_browser || true
	primary_browser=${primary_browser:-Safari}
	read -r -p "Secondary Browser (default: Chrome): " secondary_browser || true
	secondary_browser=${secondary_browser:-Chrome}
	read -r -p "Code Editor [Visual Studio Code/Sublime Text] (default: Visual Studio Code): " editor || true
	editor=${editor:-Visual Studio Code}
	read -r -p "Terminal [Terminal/iTerm] (default: Terminal): " terminal || true
	terminal=${terminal:-Terminal}

	# Detect Fabric binary to set path override (optional)
	local fabpath=""
	if command -v fabric-ai >/dev/null 2>&1; then
		fabpath="$(command -v fabric-ai)"
	elif command -v fabric >/dev/null 2>&1; then
		fabpath="$(command -v fabric)"
	fi

	# Decide whether to overwrite
	if [ "$CONFIG_CREATED" -eq 1 ] || confirm "Write a minimal overrides file to config_user.lua (backup first)?"; then
		backup_dir "$cfg"
		# Write minimal overrides file
		cat > "$cfg" <<'EOF'
-- User overrides generated by install-setup.sh
local defaults = {
	applications = {
		Browser = "__PRIMARY_BROWSER__",
		Browser2 = "__SECONDARY_BROWSER__",
		Editor = "__EDITOR__",
		Terminal = "__TERMINAL__",
	},
}
return defaults
EOF
		# Inject selected values
		sed -i '' "s|__PRIMARY_BROWSER__|${primary_browser}|g" "$cfg"
		sed -i '' "s|__SECONDARY_BROWSER__|${secondary_browser}|g" "$cfg"
		sed -i '' "s|__EDITOR__|${editor}|g" "$cfg"
		sed -i '' "s|__TERMINAL__|${terminal}|g" "$cfg"

		# If we detected a Fabric path, add it as an override by appending a small block before the return
		if [ -n "$fabpath" ]; then
			# Insert fabric block above final return
			sed -i '' $'s|return defaults|\
-- Fabric path override added by installer\
defaults.fabric = defaults.fabric or {}\
defaults.fabric.fabricPath = "'"$fabpath"'"\
\
return defaults|g' "$cfg"
		fi
		info "Wrote overrides to config_user.lua (backup created)"
	else
		warn "Skipped modifying config_user.lua; you can set apps later in that file"
	fi
}

install_hammerspoon() {
	step "Installing Hammerspoon"
	install_pkg hammerspoon
}

install_fabric() {
	step "Installing Fabric"
	if ! command -v fabric-ai >/dev/null 2>&1 && ! command -v fabric >/dev/null 2>&1; then
		install_pkg fabric-ai || true
	fi
	# Alias for convenience
	if ! grep -q "alias fabric='fabric-ai'" "$HOME/.zshrc" 2>/dev/null; then
		echo "alias fabric='fabric-ai'" >> "$HOME/.zshrc"
		info "Added alias fabric -> fabric-ai to ~/.zshrc"
	fi
}

setup_fabric_patterns() {
	step "Installing Fabric patterns"
	mkdir -p "$HOME/.config/fabric/patterns"
	if [ -d "$HOME/.hammerspoon/fabric-patterns" ]; then
		rsync -a "$HOME/.hammerspoon/fabric-patterns/" "$HOME/.config/fabric/patterns/"
		rm -rf "$HOME/.hammerspoon/fabric-patterns"
		info "Installed Fabric patterns"
	else
		warn "fabric-patterns directory not found in repo"
	fi
}

write_fabric_env() {
	step "Configuring Fabric API keys"
	local envdir="$HOME/.config/fabric"
	local envfile="$envdir/.env"
	mkdir -p "$envdir"

	# Existing values preserved
	local groq_key=""
	local yt_key=""
	if [ -f "$envfile" ]; then
		groq_key=$(grep '^GROQ_API_KEY=' "$envfile" | sed 's/^GROQ_API_KEY=//') || true
		yt_key=$(grep '^YOUTUBE_API_KEY=' "$envfile" | sed 's/^YOUTUBE_API_KEY=//') || true
	fi

	read -r -p "Groq API Key (leave blank to keep current): " in_groq || true
	read -r -p "YouTube API Key (optional): " in_yt || true

	groq_key=${in_groq:-$groq_key}
	yt_key=${in_yt:-$yt_key}

	{
		echo "# Fabric env configured by install-setup.sh"
		[ -n "$groq_key" ] && echo "GROQ_API_KEY=$groq_key"
		[ -n "$yt_key" ] && echo "YOUTUBE_API_KEY=$yt_key"
	} > "$envfile"
	chmod 600 "$envfile"
	info "Wrote $envfile"
}

configure_fabric_model() {
	step "Selecting Fabric defaults"
	local cfgdir="$HOME/.config/fabric"
	mkdir -p "$cfgdir"
	local provider="Groq"
	local model="llama-3.1-70b-versatile"
	read -r -p "Default model (enter to accept $model): " in_model || true
	model=${in_model:-$model}
	{
		echo "PROVIDER=$provider"
		echo "DEFAULT_MODEL=$model"
	} > "$cfgdir/defaults"
	info "Fabric defaults saved"
}

open_help_links() {
	step "Opening help links (you can follow along)"
	local browser_cmd="open"
	$browser_cmd "https://console.groq.com/keys"
	$browser_cmd "https://console.cloud.google.com/marketplace/product/google/youtube.googleapis.com"
}

final_notes() {
	echo
	echo -e "${GREEN}========================================${NC}"
	echo -e "${GREEN} Guided setup complete${NC}"
	echo -e "${GREEN}========================================${NC}"
	echo
	echo "Next steps:"
	echo "1) Open a new terminal so the 'fabric' alias is active"
	echo "2) Launch Hammerspoon: open -a Hammerspoon"
	echo "3) Grant Accessibility in System Settings > Privacy & Security > Accessibility"
	echo "4) Reload config (⌘⌃⌥⇧R)"
}

main() {
	step "Prerequisites"
	install_homebrew
	require_cmd brew || exit 1

	step "Install apps"
	install_hammerspoon
	clone_repo
	ensure_user_config
	set_app_defaults
	install_fabric
	setup_fabric_patterns
	write_fabric_env
	configure_fabric_model

	if confirm "Open step-by-step key setup guides in your browser now?"; then
		open_help_links
	fi

	final_notes
}

main "$@"
